[package]
name = "jupiter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
computer_config = {path = "./computer_config"}
computer = {path="./computer"}
winit = "0.27.2"
pixels = "0.9.0"
